const UNITS = [
{n:1,t:"The Most Visited Country",w:[
["because","[bɪˈkɔːz]","conj","Introduces a reason for something.","We need to study because we have a test tomorrow.","🔗"],
["east","[iːst]","n","The direction the sun rises from.","My window looks to the east.","🌅"],
["expensive","[ɪkˈspensɪv]","adj","Costs a lot of money.","My friend drives an expensive sports car.","💎"],
["flower","[ˈflaʊər]","n","The colored part of a plant.","She gave pink flowers to her grandmother.","🌸"],
["garden","[ˈɡɑːrdn]","n","An area where people grow plants.","The garden is bright in spring.","🌷"],
["holiday","[ˈhɑːlədeɪ]","n","A special day of celebration.","Monday was a holiday, so no school.","🎉"],
["many","[ˈmeni]","adj","Shows a large number of something.","There are many people on the street.","👥"],
["million","[ˈmɪljən]","n","The number 1,000,000.","Almost 19 million people live in Delhi.","🔢"],
["mountain","[ˈmaʊntn]","n","A very high hill.","Everest is the highest mountain.","🏔️"],
["place","[pleɪs]","n","A space or area.","A library is a place to read books.","📍"],
["popular","[ˈpɑːpjələr]","adj","Liked by many people.","Listening to a popular man speak.","⭐"],
["ski","[skiː]","v","To glide over snow on long boards.","The man likes to ski every weekend.","⛷️"],
["such","[sʌtʃ]","adj","Means 'like this'.","Never seen such a beautiful sunset!","✨"],
["total","[ˈtoʊtl]","n","All counted together.","The total cost was $52.","➕"],
["tower","[ˈtaʊər]","n","A tall, narrow building.","A famous tower in Italy.","🗼"],
["town","[taʊn]","n","Smaller than a city.","I come from a small town.","🏘️"],
["train","[treɪn]","n","Connected railway cars.","The train is very fast.","🚆"],
["walk","[wɔːk]","v","To move forward using legs.","Children walk to school.","🚶"],
["watch","[wɑːtʃ]","v","To look at for some time.","I came to watch a movie.","👀"],
["world","[wɜːrld]","n","The Earth and all in it.","Name the five oceans of the world.","🌍"]
]},
{n:2,t:"The Twelve Months",w:[
["anxious","[ˈæŋkʃəs]","adj","Feeling worried or nervous.","She was anxious about being late.","😰"],
["awful","[ˈɔːfl]","adj","Very bad.","Her performance was awful.","👎"],
["consist","[kənˈsɪst]","v","To be made of parts.","Lunch consisted of pizza and salad.","🧩"],
["desire","[dɪˈzaɪər]","v","To want something.","My sister desires a big house.","💭"],
["eager","[ˈiːɡər]","adj","Excited about something.","He was eager to share the news.","🤩"],
["household","[ˈhaʊshoʊld]","n","All people in one house.","Our household has three people.","🏠"],
["intent","[ɪnˈtent]","n","A plan to do something.","Her intent was to visit Italy.","🎯"],
["landscape","[ˈlændskeɪp]","n","How an area of land looks.","The landscape is very green.","🏞️"],
["lift","[lɪft]","v","To move something higher.","He tried to lift the box.","⬆️"],
["load","[loʊd]","v","To put objects into something.","The man loaded the boxes into a truck.","📦"],
["lung","[lʌŋ]","n","Body part for breathing.","Strong lungs are important.","🫁"],
["motion","[ˈmoʊʃn]","n","Movement.","January made a motion with his hand.","🌀"],
["pace","[peɪs]","n","Speed of movement.","She walked at a slow pace.","🚶"],
["polite","[pəˈlaɪt]","adj","Being nice and respectful.","He gave a polite thank you.","🙏"],
["possess","[pəˈzes]","v","To have or own.","She possessed feelings of hate.","🔑"],
["rapidly","[ˈræpɪdli]","adv","Very fast.","The days passed rapidly.","⚡"],
["remark","[rɪˈmɑːrk]","v","To say something.","Anna's stepmother remarked about flowers.","💬"],
["seek","[siːk]","v","To look for.","They went to seek the twelve months.","🔍"],
["shine","[ʃaɪn]","v","To make light.","March made the sun shine.","☀️"],
["spill","[spɪl]","v","To make something fall out.","She spilled the flowers on the table.","💧"]
]},
{n:3,t:"The Battle of Thermopylae",w:[
["arrow","[ˈæroʊ]","n","A stick shot from a bow.","The arrow hit the target.","🏹"],
["battle","[ˈbætl]","n","A fight between armies.","The battle lasted many days.","⚔️"],
["bow","[boʊ]","n","A weapon that shoots arrows.","He went hunting with a bow.","🎯"],
["brave","[breɪv]","adj","Not afraid of danger.","The brave firefighter saved the girl.","🦁"],
["chief","[tʃiːf]","n","Leader of a group.","The chief led through mountains.","👑"],
["disadvantage","[ˌdɪsədˈvæntɪdʒ]","n","A hard situation.","Mike had a disadvantage in the race.","⚠️"],
["enemy","[ˈenəmi]","n","A country at war with another.","The enemy prepared to attack.","🎭"],
["entrance","[ˈentrəns]","n","A place to enter.","Bill had to find a different entrance.","🚪"],
["hardly","[ˈhɑːrdli]","adv","In a very small way.","I hardly saw the concert.","👁️"],
["intend","[ɪnˈtend]","v","To plan to do.","I intend to finish college in three years.","🗓️"],
["laughter","[ˈlæftər]","n","Sound of laughing.","Her joke caused laughter.","😂"],
["log","[lɔːɡ]","n","A thick piece of wood.","We added another log to the fire.","🪵"],
["military","[ˈmɪləteri]","n","Armed forces.","I joined the military after school.","🎖️"],
["obey","[əˈbeɪ]","v","To follow orders.","My sister did not obey my mother.","🙇"],
["secure","[sɪˈkjʊr]","v","To get after effort.","I secured a good grade.","🔒"],
["steady","[ˈstedi]","adj","Not changing much.","She remained steady and solved it.","🧘"],
["trust","[trʌst]","v","To believe someone is honest.","I trust my friends.","🤝"],
["twist","[twɪst]","v","To turn around.","She twisted spaghetti on her fork.","🍝"],
["unless","[ənˈles]","conj","If not, except when.","Unless you clean your room, no playing.","❓"],
["weapon","[ˈwepən]","n","Object used to hurt.","Swords were used as weapons for years.","🗡️"]
]},
{n:4,t:"The Deer and His Image",w:[
["chest","[tʃest]","n","Front body between neck and stomach.","The water was as high as my chest.","🫀"],
["confidence","[ˈkɑːnfɪdəns]","n","A feeling of certainty.","I have confidence that I did well.","💪"],
["consequence","[ˈkɑːnsɪkwens]","n","A result of action.","As a consequence of missing the bus...","➡️"],
["disaster","[dɪˈzæstər]","n","A really bad event.","When the car crashed, it was a disaster.","💥"],
["disturb","[dɪˈstɜːrb]","v","To upset someone.","The noise disturbed me while working.","😤"],
["estimate","[ˈestɪmeɪt]","v","To make a guess.","He estimated he was one meter tall.","📏"],
["honor","[ˈɑːnər]","v","To show respect.","We honor those who died for their country.","🎗️"],
["impress","[ɪmˈpres]","v","To make someone proud.","He impressed the girls with his dance.","🌟"],
["narrow","[ˈnæroʊ]","adj","Thin, not wide.","The bridge is too narrow for a car.","📐"],
["pale","[peɪl]","adj","Not bright in color.","The girl's skin was very pale.","🫥"],
["rough","[rʌf]","adj","Not even or smooth.","The rough ground hurt my feet.","🪨"],
["satisfy","[ˈsætɪsfaɪ]","v","To make happy.","It will satisfy my teacher if I finish homework.","😊"],
["scream","[skriːm]","v","To make a loud noise.","The girl saw a spider and screamed.","😱"],
["sensitive","[ˈsensətɪv]","adj","Easily hurt.","My teeth are sensitive to cold.","🦷"],
["shade","[ʃeɪd]","n","Dark area from blocked sun.","The boy sat in the shade of a tree.","🌳"],
["strength","[streŋkθ]","n","Ability to do hard work.","Eating well builds strength.","💪"],
["supplement","[ˈsʌplɪment]","v","To add something good.","He supplements his diet with fruit.","🍎"],
["terror","[ˈterər]","n","Very strong fear.","I felt terror when the tiger chased me.","😨"],
["threat","[θret]","n","Something bad that might happen.","There was a threat of a storm.","⛈️"],
["victim","[ˈvɪktɪm]","n","Person hurt by bad action.","I was a victim of a robbery.","🩹"]
]},
{n:5,t:"May 29, 1953",w:[
["ancestor","[ˈænsestər]","n","Family member from the past.","My ancestors came from Germany.","👴"],
["angle","[ˈæŋɡl]","n","Direction from which something is seen.","The giraffe turned to see another angle.","📐"],
["boot","[buːt]","n","Heavy shoe above the ankle.","He wore boots so his feet wouldn't get wet.","🥾"],
["border","[ˈbɔːrdər]","n","Edge of an area.","Postcard had a green border.","🔲"],
["congratulate","[kənˈɡrætʃuleɪt]","v","To tell someone you're happy for them.","Bill and Angela congratulated each other.","🎊"],
["frame","[freɪm]","n","Border for a picture.","I need a frame for my friend's picture.","🖼️"],
["heaven","[ˈhevn]","n","Place some believe people go after death.","When I die, I hope to go to heaven.","☁️"],
["incredible","[ɪnˈkredəbl]","adj","So amazing it's hard to believe.","I have an incredible story for you.","🤯"],
["legend","[ˈledʒənd]","n","Story from the past.","There's a well-known legend about a king.","📜"],
["praise","[preɪz]","v","To show you like something.","The coach praised the athletes.","👏"],
["proceed","[prəˈsiːd]","v","To go or continue.","It was time to proceed down the mountain.","➡️"],
["pure","[pjʊr]","adj","Not mixed with anything.","The snow looked pure.","💎"],
["relative","[ˈrelətɪv]","n","Family member.","I sent messages to my relatives.","👨‍👩‍👧"],
["senior","[ˈsiːniər]","adj","Older or more experienced.","I was the senior explorer in my group.","🔝"],
["silent","[ˈsaɪlənt]","adj","Having no sound.","The air was silent.","🤫"],
["sink","[sɪŋk]","v","To go down under water.","My boots sank into the snow.","⬇️"],
["superior","[suːˈpɪriər]","n","Person of higher rank.","My superior John Hunt praised us.","⭐"],
["surround","[səˈraʊnd]","v","To close in from all sides.","I looked at the beauty that surrounded me.","🔄"],
["thick","[θɪk]","adj","Wide and solid.","The snow was very thick.","🧱"],
["wrap","[ræp]","v","To cover by folding.","I wrapped my coat around my body.","🧥"]
]},
{n:6,t:"Ways to Reduce Stress",w:[
["also","[ˈɔːlsoʊ]","adv","In addition, too.","I like blue, and I also like yellow.","➕"],
["automatically","[ˌɔːtəˈmætɪkli]","adv","Without thinking.","He automatically smiled.","🤖"],
["busy","[ˈbɪzi]","adj","Having a lot to do.","Everyone is busy at the office.","🏃"],
["can","[kæn]","aux","Shows ability to do.","Sad news can make her cry.","💪"],
["clear","[klɪr]","v","To remove everything.","I need to clear my desk.","🧹"],
["close","[kloʊz]","v","To shut something.","He wanted to close the door tightly.","🚪"],
["discuss","[dɪˈskʌs]","v","To talk about with someone.","James began to discuss his report.","💬"],
["feel","[fiːl]","v","To experience emotion.","The girl must feel happy.","💗"],
["listen","[ˈlɪsn]","v","To pay attention to sound.","Lisa wanted to listen carefully.","👂"],
["meet","[miːt]","v","To come together.","Ken's mother wanted to meet his teacher.","🤝"],
["music","[ˈmjuːzɪk]","n","Sound made by singing or instruments.","The boy makes music by playing guitar.","🎵"],
["normal","[ˈnɔːrml]","adj","Usual, not strange.","It's normal to wear uniforms.","✅"],
["quiet","[ˈkwaɪət]","adj","Not much sound.","The man told children to be quiet.","🤫"],
["relax","[rɪˈlæks]","v","To rest or enjoy.","Nicole likes to relax by reading.","🧘"],
["sleep","[sliːp]","v","To rest mind and body.","The child goes to sleep at night.","😴"],
["stress","[stres]","n","Strong feeling of worry.","Dan has a lot of stress at work.","😖"],
["study","[ˈstʌdi]","v","To learn by reading.","She needed a quiet place to study.","📚"],
["talk","[tɔːk]","v","To say words to express thoughts.","They went to talk to each other.","🗣️"],
["work","[wɜːrk]","v","To do a job for pay.","They need to work together.","💼"],
["write","[raɪt]","v","To make letters with pen.","I need to write a story for homework.","✍️"]
]},
{n:7,t:"A Beautiful Bird",w:[
["basis","[ˈbeɪsɪs]","n","Main part or amount.","Grandfather gets hearing checked yearly.","📊"],
["biology","[baɪˈɑːlədʒi]","n","Study of living things.","We learned about the heart in biology.","🧬"],
["cage","[keɪdʒ]","n","Holds an animal so it can't leave.","We put parrots in their cage.","🦜"],
["colleague","[ˈkɑːliːɡ]","n","Someone you work with.","My colleague helped me finish.","👥"],
["colony","[ˈkɑːləni]","n","Country controlled by another.","USA was a colony of Great Britain.","🏴"],
["debate","[dɪˈbeɪt]","v","To seriously discuss.","The couple debated which TV to buy.","🗣️"],
["depart","[dɪˈpɑːrt]","v","To leave for another place.","The plane departed for Italy.","✈️"],
["depress","[dɪˈpres]","v","To make someone sad.","The bad news depressed the man.","😔"],
["factual","[ˈfæktʃuəl]","adj","With true details.","John learns from factual books.","📖"],
["fascinate","[ˈfæsɪneɪt]","v","To make very interested.","The kitten was fascinated by yarn.","😍"],
["mission","[ˈmɪʃn]","n","Important job, sometimes far away.","Her mission was to help sick people.","🎯"],
["nevertheless","[ˌnevərðəˈles]","adv","In spite of that.","Dr. Norton nevertheless believed the bird was real.","🔄"],
["occupation","[ˌɑːkjuˈpeɪʃn]","n","A person's job.","Dr. Norton's occupation was a scholar.","💼"],
["overseas","[ˌoʊvərˈsiːz]","adv","In a foreign country.","He met a sailor from overseas.","🌊"],
["persuade","[pərˈsweɪd]","v","To make someone believe.","He tried to persuade them.","💬"],
["route","[ruːt]","n","Way from one place to another.","On the route back, he passed ruins.","🗺️"],
["ruins","[ˈruːɪnz]","n","Destroyed buildings.","He walked past some old ruins.","🏛️"],
["scholar","[ˈskɑːlər]","n","Person who studies.","Dr. Norton was a scholar of biology.","🎓"],
["significant","[sɪɡˈnɪfɪkənt]","adj","Very important.","He made a significant discovery.","⭐"],
["volcano","[vɑːlˈkeɪnoʊ]","n","Mountain that erupts.","It lives by the volcano.","🌋"]
]},
{n:8,t:"Tricky Turtle",w:[
["broad","[brɔːd]","adj","Wide, not narrow.","The river is very long and broad.","🌊"],
["bush","[bʊʃ]","n","Small woody plant.","Dad and I planted bushes around the house.","🌿"],
["capable","[ˈkeɪpəbl]","adj","Able to do.","The Olympic athlete is capable of lifting a lot.","💪"],
["cheat","[tʃiːt]","v","To be dishonest to win.","They cheated on the test.","❌"],
["concentrate","[ˈkɑːnsntreɪt]","v","To give full attention.","I couldn't concentrate on homework.","🎯"],
["conclude","[kənˈkluːd]","v","To arrive at a logical end.","I concluded he ate my cookie.","🤔"],
["confident","[ˈkɑːnfɪdənt]","adj","Believing you can do it.","She was confident she could climb.","😎"],
["considerable","[kənˈsɪdərəbl]","adj","Large in size or amount.","They paid a considerable amount.","📊"],
["convey","[kənˈveɪ]","v","To communicate ideas.","That picture conveys sadness.","💬"],
["definite","[ˈdefɪnət]","adj","Certain, sure to be true.","There's a definite connection.","✔️"],
["delight","[dɪˈlaɪt]","n","Feeling very happy.","He felt such delight after promotion.","🎉"],
["destination","[ˌdestɪˈneɪʃn]","n","Place someone is going to.","The destination is Munich.","📍"],
["edge","[edʒ]","n","Furthest side of something.","He ran to the edge of the cliff.","📐"],
["instructions","[ɪnˈstrʌkʃnz]","n","Explains how to do something.","Follow the instructions.","📋"],
["path","[pæθ]","n","Way people can walk.","We followed a path through the woods.","🛤️"],
["resort","[rɪˈzɔːrt]","v","To depend on to solve.","I hope they don't resort to violence.","🆘"],
["shadow","[ˈʃædoʊ]","n","Dark area from blocked light.","The man's shadow was taller.","🌑"],
["succeed","[səkˈsiːd]","v","To complete as planned.","He will work until he succeeds.","🏆"],
["suspect","[səˈspekt]","v","To believe might be true.","I suspect those kids stole money.","🔍"],
["valley","[ˈvæli]","n","Low land between hills.","We looked at the valley below.","🏞️"]
]},
{n:9,t:"The Starfish",w:[
["against","[əˈɡenst]","prep","Touching or opposed to.","They leaned against the wall.","🚧"],
["beach","[biːtʃ]","n","Sandy place by the ocean.","The girl built a sandcastle on the beach.","🏖️"],
["damage","[ˈdæmɪdʒ]","v","To break something.","The car was damaged in the accident.","💥"],
["discover","[dɪˈskʌvər]","v","To find for the first time.","I discovered new information.","🔍"],
["emotion","[ɪˈmoʊʃn]","n","How you feel.","Anger is a common emotion.","❤️"],
["fix","[fɪks]","v","To make something work.","Dad has tools to fix broken things.","🔧"],
["identify","[aɪˈdentɪfaɪ]","v","To find out what it is.","I used the file to identify his name.","🔎"],
["island","[ˈaɪlənd]","n","Land in the middle of water.","Japan is a group of islands.","🏝️"],
["ocean","[ˈoʊʃn]","n","All salt water around land.","The ocean makes powerful waves.","🌊"],
["perhaps","[pərˈhæps]","adv","Could happen.","Perhaps I will eat an apple.","❓"],
["pleasant","[ˈpleznt]","adj","Enjoyable.","The character had a pleasant look.","😊"],
["prevent","[prɪˈvent]","v","To stop from happening.","Handcuffs prevented me from moving.","🛑"],
["rock","[rɑːk]","n","Hard thing in the dirt.","I stacked rocks on top of each other.","🪨"],
["save","[seɪv]","v","To keep from harm.","I want to help save the world.","💚"],
["smile","[smaɪl]","v","To show happiness with mouth.","The baby smiled at me.","😊"],
["step","[step]","v","To walk.","Be careful where you step.","👣"],
["still","[stɪl]","adv","Situation keeps going.","They are still waiting in line.","⏳"],
["taste","[teɪst]","n","Flavor in your mouth.","The taste of the fruit was sweet.","👅"],
["throw","[θroʊ]","v","To make something go through air.","The pitcher can throw fast.","🎯"],
["wave","[weɪv]","n","Line of water moving higher.","The water had large blue waves.","🌊"]
]},
{n:10,t:"Blackbeard",w:[
["citizen","[ˈsɪtɪzn]","n","Someone who lives in a place.","Carlos is a Spanish citizen.","🪪"],
["council","[ˈkaʊnsl]","n","Group who runs a city.","The council met to discuss laws.","🏛️"],
["declare","[dɪˈkler]","v","To say something officially.","I declared my love for him.","📢"],
["enormous","[ɪˈnɔːrməs]","adj","Very large.","My dog looks enormous next to yours.","🐘"],
["extraordinary","[ɪkˈstrɔːrdəneri]","adj","Amazing.","The fireman was extraordinary.","✨"],
["fog","[fɔːɡ]","n","Thick cloud near ground.","I don't want to drive in thick fog.","🌫️"],
["funeral","[ˈfjuːnərəl]","n","Ceremony after death.","They had a funeral for the soldier.","⚱️"],
["giant","[ˈdʒaɪənt]","adj","Very big.","The giant truck got in my way.","🦣"],
["impression","[ɪmˈpreʃn]","n","Way of thinking about someone.","Most people's first impression of Dr. Giani...","💭"],
["intention","[ɪnˈtenʃn]","n","What a person plans to do.","Do you have good intentions?","🎯"],
["mad","[mæd]","adj","Angry.","Mother got mad when I didn't listen.","😠"],
["ought","[ɔːt]","aux","Right thing to do.","I ought to take my library books back.","✔️"],
["resist","[rɪˈzɪst]","v","To fight against.","He resisted the treatment.","🛡️"],
["reveal","[rɪˈviːl]","v","To show something.","I'll reveal where I hid the candy.","👁️"],
["rid","[rɪd]","v","To make a place free from.","We rid our home of mice using traps.","🧹"],
["sword","[sɔːrd]","n","Long sharp weapon.","They used swords in ancient battles.","🗡️"],
["tale","[teɪl]","n","A story.","She told her friends about the wild tale.","📖"],
["trap","[træp]","v","To capture so they can't escape.","We trapped butterflies in a net.","🕸️"],
["trial","[ˈtraɪəl]","n","Court process to decide guilt.","He went on trial for robbing a bank.","⚖️"],
["violent","[ˈvaɪələnt]","adj","Using force to hurt.","He was jailed because he was violent.","💢"]
]},
{n:11,t:"Dinosaur Drawings",w:[
["admission","[ədˈmɪʃn]","n","Act of allowing to enter.","Admission to the movie was $5.","🎟️"],
["astronomy","[əˈstrɑːnəmi]","n","Study of stars and planets.","Harold loved astronomy.","🔭"],
["blame","[bleɪm]","v","To say someone did something bad.","Mom blamed me for something I didn't do.","👆"],
["chemistry","[ˈkemɪstri]","n","Study of substances.","Professor taught chemical reactions in chemistry.","🧪"],
["despite","[dɪˈspaɪt]","prep","Shows difference from expected.","We played despite the cold weather.","🌧️"],
["dinosaur","[ˈdaɪnəsɔːr]","n","Big animal from long ago.","I like to see dinosaur bones at the museum.","🦕"],
["exhibit","[ɪɡˈzɪbɪt]","v","To show so people can look.","My painting will be exhibited at the fair.","🖼️"],
["fame","[feɪm]","n","Reputation among public.","He had fame and fortune but wasn't happy.","🌟"],
["forecast","[ˈfɔːrkæst]","n","Idea about future weather.","The forecast says it will rain all week.","🌦️"],
["genius","[ˈdʒiːniəs]","n","Very smart person.","Since she was a genius, she passed easily.","🧠"],
["gentle","[ˈdʒentl]","adj","Not rough.","He taught his dinosaur to be gentle.","🕊️"],
["geography","[dʒiˈɑːɡrəfi]","n","Study of Earth's features.","He took a geography test.","🌍"],
["interfere","[ˌɪntərˈfɪr]","v","To get in the way.","Mother interfered about the garbage.","🚫"],
["lightly","[ˈlaɪtli]","adv","Without much force.","He drew lightly on paper.","🪶"],
["principal","[ˈprɪnsəpl]","n","Head of a school.","She sent him to the principal.","🏫"],
["row","[roʊ]","n","A line of things.","He sat in the third row.","➖"],
["shelf","[ʃelf]","n","Flat board for storage.","He put his umbrella on the shelf.","📚"],
["spite","[spaɪt]","n","Desire to hurt.","She sent him out of spite.","😾"],
["super","[ˈsuːpər]","adj","Very good.","His idea was super.","👍"],
["wet","[wet]","adj","Covered in water.","He was all wet from the rain.","💧"]
]},
{n:12,t:"The Mean Chef",w:[
["abuse","[əˈbjuːz]","v","To hurt on purpose.","The mean man abused his dog.","😡"],
["afford","[əˈfɔːrd]","v","To have enough money.","I saved money to afford a new bike.","💰"],
["bake","[beɪk]","v","To cook in an oven.","My sister bakes delicious cakes.","🍰"],
["bean","[biːn]","n","Plant seed good to eat.","Many different kinds of beans.","🫘"],
["candle","[ˈkændl]","n","Wax stick lit for light.","When lights went out, we lit candles.","🕯️"],
["convert","[kənˈvɜːrt]","v","To change into something else.","He converted his field into a garden.","🔄"],
["debt","[det]","n","Money a person owes.","I owe a debt to the gas company.","💸"],
["decrease","[dɪˈkriːs]","v","To make less.","Hiring police decreased crime.","📉"],
["fault","[fɔːlt]","n","Responsibility for mistake.","It's my fault the cat ran away.","❗"],
["fund","[fʌnd]","n","Amount of money people have.","We put money into our club's fund.","🏦"],
["generous","[ˈdʒenərəs]","adj","Likes to give things.","The generous man donated computers.","🎁"],
["ingredient","[ɪnˈɡriːdiənt]","n","Part of a food dish.","Eggs, sugar, flour are cake ingredients.","🥚"],
["insist","[ɪnˈsɪst]","v","To be firm about what to do.","I insist that you try these cookies.","💪"],
["mess","[mes]","n","Condition that's not clean.","Heather's room was a complete mess.","🧹"],
["metal","[ˈmetl]","n","Strong material for building.","Steel is a common metal.","🔨"],
["monitor","[ˈmɑːnɪtər]","v","To watch closely.","The teacher monitors the students.","👁️"],
["oppose","[əˈpoʊz]","v","To act against.","I want to be a police officer because I oppose crime.","✋"],
["passive","[ˈpæsɪv]","adj","Not taking action.","Marcie is so passive, she never solves problems.","😐"],
["quantity","[ˈkwɑːntəti]","n","A certain amount.","I have a small quantity of milk.","⚖️"],
["sue","[suː]","v","To take to court.","I sued the company after slipping.","⚖️"]
]},
{n:13,t:"The Cat and the Fox",w:[
["adequate","[ˈædɪkwət]","adj","Good enough.","This is adequate for my needs.","✔️"],
["anxiety","[æŋˈzaɪəti]","n","Feeling of worry and fear.","When I climb to high places, I'm filled with anxiety.","😰"],
["army","[ˈɑːrmi]","n","Large group who fight in wars.","The army protects all the people.","🎖️"],
["billion","[ˈbɪljən]","n","Number 1,000,000,000.","Billions of stars in outer space.","🔢"],
["carve","[kɑːrv]","v","To cut into something.","Dad carves the turkey on Thanksgiving.","🔪"],
["consult","[kənˈsʌlt]","v","To ask for help.","I'll consult my accountant.","💼"],
["emergency","[ɪˈmɜːrdʒənsi]","n","Time to help right away.","There is a fire in my house! Emergency!","🚨"],
["fortune","[ˈfɔːrtʃuːn]","n","Things not controlled by people.","I have good fortune when I play cards.","🍀"],
["guarantee","[ˌɡærənˈtiː]","v","To promise something.","I guarantee the loan will be repaid.","🤝"],
["initial","[ɪˈnɪʃl]","adj","First.","The initial step is to find a topic.","1️⃣"],
["intense","[ɪnˈtens]","adj","Very strong.","The skunk made an intense odor.","🔥"],
["lend","[lend]","v","To give for short time.","My sister lost her pen, so I'll lend her mine.","🤲"],
["peak","[piːk]","n","Very top of a mountain.","There is snow on the peaks.","⛰️"],
["potential","[pəˈtenʃl]","adj","Capable of being.","I've thought of some potential problems.","💡"],
["pride","[praɪd]","n","Happiness about oneself.","I take pride in getting good grades.","🦁"],
["proof","[pruːf]","n","Fact that shows something is real.","They used his fingerprint as proof.","🔬"],
["quit","[kwɪt]","v","To stop doing.","I quit running because I got tired.","🛑"],
["spin","[spɪn]","v","To turn in circles.","The boy kept spinning until he fell.","🌀"],
["tiny","[ˈtaɪni]","adj","Very small.","A baby's hand is tiny.","🐜"],
["tutor","[ˈtuːtər]","n","Gives lessons to one student.","My mother hired a tutor to help her.","👩‍🏫"]
]},
{n:14,t:"The Good Student",w:[
["apparent","[əˈpærənt]","adj","Clear or easy to see.","Her happiness was apparent from her smile.","👀"],
["blind","[blaɪnd]","adj","Cannot see.","The blind man didn't see the hole.","🙈"],
["calculate","[ˈkælkjuleɪt]","v","To find an answer using math.","I calculated how much money I'd need.","🧮"],
["chat","[tʃæt]","v","To talk with someone.","They chatted every day.","💬"],
["commit","[kəˈmɪt]","v","To promise to do.","He had committed to finishing the job.","🤝"],
["compose","[kəmˈpoʊz]","v","To make from smaller parts.","Tony composed his report using sources.","📝"],
["dormitory","[ˈdɔːrmətɔːri]","n","School building for students.","I'll move into the dormitory.","🏢"],
["exhaust","[ɪɡˈzɔːst]","v","To make tired.","John exhausted himself by swimming.","😩"],
["greenhouse","[ˈɡriːnhaʊs]","n","Small glass building for plants.","We have a greenhouse in our backyard.","🌱"],
["ignore","[ɪɡˈnɔːr]","v","To act like you don't see.","I ignored the message and kept studying.","🙉"],
["obvious","[ˈɑːbviəs]","adj","Clear or easy to see.","It was obvious that he was tired.","❗"],
["physics","[ˈfɪzɪks]","n","Science of energy and matter.","In physics class we used Newton's Cradle.","⚛️"],
["portion","[ˈpɔːrʃn]","n","Part of something.","I only ate a small portion.","🍕"],
["remind","[rɪˈmaɪnd]","v","To tell to remember.","Nick's dad reminded him about homework.","⏰"],
["secretary","[ˈsekrəteri]","n","Person who works in an office.","Rebecca asked her secretary to type a report.","💼"],
["severe","[sɪˈvɪr]","adj","Very bad or serious.","After hitting his hand, Sam was in severe pain.","⚠️"],
["talent","[ˈtælənt]","n","Natural ability.","Maria has a talent for piano.","🎹"],
["thesis","[ˈθiːsɪs]","n","Idea that needs proof.","She didn't support her thesis well.","📜"],
["uniform","[ˈjuːnɪfɔːrm]","n","Clothing worn by a group.","Our marching band wears matching uniforms.","👔"],
["vision","[ˈvɪʒn]","n","Ability to see.","The eye doctor tested my vision.","👁️"]
]},
{n:15,t:"The Lucky Knife",w:[
["absorb","[əbˈzɔːrb]","v","To take inside.","He used a sponge to absorb water.","🧽"],
["boss","[bɔːs]","n","Person in charge.","My boss is a nice person.","👨‍💼"],
["charitable","[ˈtʃærətəbl]","adj","Aims to help people.","I give money to a charitable foundation.","❤️"],
["committee","[kəˈmɪti]","n","Group who meets to decide.","The committee agreed on a new dress code.","🏛️"],
["contract","[ˈkɑːntrækt]","n","Written agreement.","She signed a contract when buying the house.","📝"],
["crew","[kruː]","n","Group of people working together.","I was part of a crew of students.","👷"],
["devote","[dɪˈvoʊt]","v","To give one's life to.","He devoted his life to studying generations.","🙇"],
["dig","[dɪɡ]","v","To break up earth.","I began to dig in the soil.","⛏️"],
["dine","[daɪn]","v","To eat.","We dined on what we could find.","🍽️"],
["donate","[ˈdoʊneɪt]","v","To give.","My uncle donated all of the things.","🎁"],
["double","[ˈdʌbl]","adj","Twice as much.","I paid almost double the amount.","✖️2"],
["flavor","[ˈfleɪvər]","n","Taste of food or drinks.","The ice cream flavor was very good.","🍦"],
["foundation","[faʊnˈdeɪʃn]","n","Group that provides money.","The foundation raised money for scholarships.","🏛️"],
["generation","[ˌdʒenəˈreɪʃn]","n","Group of people of same time.","Grandparents are from a different generation.","👨‍👩‍👧"],
["handle","[ˈhændl]","n","Part of object people hold.","Pick up the pot by the handle.","🫳"],
["layer","[ˈleɪər]","n","One of several pieces on top.","There was a layer of snow on the houses.","📚"],
["mud","[mʌd]","n","Soft, wet dirt.","My brother played rugby in the mud.","🟤"],
["smooth","[smuːð]","adj","No bumps or rough parts.","The baby's skin felt very smooth.","🤲"],
["soil","[sɔɪl]","n","Top layer of land.","The boy planted flowers in the soil.","🌱"],
["unique","[juˈniːk]","adj","Not like others.","Her dog is unique.","🌟"]
]},
{n:16,t:"Adams County's Gold",w:[
["academy","[əˈkædəmi]","n","Special type of school.","Many courses are taught at the academy.","🏫"],
["ancient","[ˈeɪnʃənt]","adj","Very old.","I want to see ancient buildings in Rome.","🏛️"],
["board","[bɔːrd]","n","Flat piece of wood.","The sign was made of wooden boards.","🪵"],
["century","[ˈsentʃəri]","n","One hundred years.","Our company is celebrating a century.","💯"],
["clue","[kluː]","n","Fact that helps solve mystery.","The detective found clues on the sidewalk.","🔍"],
["concert","[ˈkɑːnsərt]","n","Event with music.","I enjoyed the concert last night.","🎸"],
["county","[ˈkaʊnti]","n","Largest division of a state.","He represented the citizens of his county.","🗺️"],
["dictionary","[ˈdɪkʃəneri]","n","Book with word meanings.","I use the dictionary to learn new words.","📕"],
["exist","[ɪɡˈzɪst]","v","To be real.","Do you think unicorns ever existed?","🌀"],
["flat","[flæt]","adj","Level and smooth.","My parents bought a flat-screen TV.","📺"],
["gentleman","[ˈdʒentlmən]","n","Polite man.","He is a nice gentleman.","🎩"],
["hidden","[ˈhɪdn]","adj","Not able to be seen.","It's about hidden gold in Adams County.","🕵️"],
["maybe","[ˈmeɪbi]","adv","Possible.","Maybe there is gold!","❓"],
["officer","[ˈɔːfɪsər]","n","Leader in the army.","An officer in the army.","🎖️"],
["original","[əˈrɪdʒənl]","adj","First of its kind.","It has the original cover.","1️⃣"],
["pound","[paʊnd]","v","To hit many times.","Brad pounded on the board until it broke.","👊"],
["process","[ˈprɑːses]","n","Steps to do something.","The process made them hungry.","🔄"],
["publish","[ˈpʌblɪʃ]","v","To make a book.","It was published in 1870!","📚"],
["theater","[ˈθiːətər]","n","Place to watch movies.","He asked Jeff to go to the movie theater.","🎬"],
["wealth","[welθ]","n","A lot of money.","Hidden gold in Adams County wealth.","💰"]
]},
{n:17,t:"Henry Ford's Famous Car",w:[
["aim","[eɪm]","n","A goal.","My aim is to become a helicopter pilot.","🎯"],
["attach","[əˈtætʃ]","v","To put two things together.","I attached socks to the clothesline.","📎"],
["bet","[bet]","v","To risk money.","How much will you bet on your horse?","🎲"],
["carriage","[ˈkærɪdʒ]","n","Vehicle pulled by horse.","We took a carriage ride in the park.","🐴"],
["classic","[ˈklæsɪk]","adj","Common from the past.","The athlete made a classic mistake.","🏛️"],
["commute","[kəˈmjuːt]","v","To travel to work.","I commute to work on the train.","🚆"],
["confirm","[kənˈfɜːrm]","v","To make sure correct.","Winning confirmed that James was a good player.","✔️"],
["criticize","[ˈkrɪtɪsaɪz]","v","To say bad things.","He criticized his wife for spending.","👎"],
["differ","[ˈdɪfər]","v","To not be the same.","I differ from my brother.","↔️"],
["expense","[ɪkˈspens]","n","Money spent.","She wrote down all the expenses.","💸"],
["formal","[ˈfɔːrml]","adj","Official or serious.","It was a formal dinner.","🎩"],
["height","[haɪt]","n","How tall something is.","My height is 168 centimeters.","📏"],
["invent","[ɪnˈvent]","v","To create first time.","Grandfather has invented interesting things.","💡"],
["junior","[ˈdʒuːniər]","adj","Younger or less experienced.","She was only a junior manager.","🔽"],
["labor","[ˈleɪbər]","n","Act of making something.","Building the house took a lot of labor.","🛠️"],
["mechanic","[məˈkænɪk]","n","Fixes vehicles.","We took the car to the mechanic.","🔧"],
["prime","[praɪm]","adj","Most important.","Dirty air is a prime cause of illness.","1️⃣"],
["shift","[ʃɪft]","v","To move to a different place.","He shifted to the other side.","↔️"],
["signal","[ˈsɪɡnəl]","n","Sound telling someone to do.","Coach blew his whistle as a signal.","🔔"],
["sincere","[sɪnˈsɪr]","adj","Honest.","He sounded sincere when he apologized.","🙏"]
]},
{n:18,t:"The Priest",w:[
["ability","[əˈbɪləti]","n","Quality of being able.","His swimming abilities let him cross the lake.","💪"],
["agriculture","[ˈæɡrɪkʌltʃər]","n","Growing plants and animals for food.","The farmer studied agriculture.","🌾"],
["cartoon","[kɑːrˈtuːn]","n","Funny drawing.","People draw cartoons for newspapers.","🎨"],
["ceiling","[ˈsiːlɪŋ]","n","Top of a room.","He painted the ceiling.","⬆️"],
["convince","[kənˈvɪns]","v","To make sure of something.","She convinced me to buy the house.","💬"],
["curious","[ˈkjʊriəs]","adj","Wants to know.","I opened the clock because I was curious.","🤔"],
["delay","[dɪˈleɪ]","v","To wait to do.","I was delayed at the airport for two hours.","⏳"],
["diary","[ˈdaɪəri]","n","Book for personal experiences.","I don't let anybody read my diary.","📔"],
["element","[ˈeləmənt]","n","Particular part of something.","Tackling is Johnny's favorite element of football.","🧩"],
["faith","[feɪθ]","n","Trust without proof.","The sick girl had faith in doctors.","🙏"],
["grain","[ɡreɪn]","n","Food crop like wheat.","The farmer planted grain this year.","🌾"],
["greet","[ɡriːt]","v","To welcome.","They greeted him and let him in.","👋"],
["investigate","[ɪnˈvestɪɡeɪt]","v","To search for.","Investigate the elements of your life you love.","🔍"],
["joy","[dʒɔɪ]","n","Feeling of happiness.","He was good at his profession but had no joy.","😄"],
["label","[ˈleɪbl]","n","Tag that tells about something.","He made his own labels for jars of jam.","🏷️"],
["monk","[mʌŋk]","n","Religious man.","He visited a group of monks.","🧘"],
["odd","[ɑːd]","adj","Strange.","The priest thought the answer was odd.","❓"],
["pause","[pɔːz]","v","To stop.","The wise monks paused for a minute.","⏸️"],
["priest","[priːst]","n","Person who performs religious duties.","A young priest was always sad.","⛪"],
["profession","[prəˈfeʃn]","n","A job.","He was good at his profession.","💼"]
]},
{n:19,t:"Strange and Unusual Jobs",w:[
["ball","[bɔːl]","n","Round object for games.","Seth bought a new soccer ball.","⚽"],
["bottom","[ˈbɑːtəm]","n","Lowest part.","Sarah's feet can touch the bottom of the pool.","⬇️"],
["company","[ˈkʌmpəni]","n","Business that makes or sells.","I want to work for a small software company.","🏢"],
["drink","[drɪŋk]","v","To take liquid.","The woman likes to drink water.","🥤"],
["few","[fjuː]","adj","Small number.","I have only a few coins.","🔢"],
["line","[laɪn]","n","Row of people or things.","This is the longest line I've ever seen.","➖"],
["pet","[pet]","n","Animal people keep and care for.","Tyler likes spending time with his pet dog.","🐕"],
["product","[ˈprɑːdʌkt]","n","Something made to be sold.","No room for even one more product.","📦"],
["responsible","[rɪˈspɑːnsəbl]","adj","In charge of something.","Peter is responsible for leading his department.","👔"],
["sell","[sel]","v","To give for money.","This man's job is to sell houses.","💰"],
["snake","[sneɪk]","n","Animal with long body and no legs.","Be careful of the snake in the tree.","🐍"],
["stand","[stænd]","v","To use legs to hold body upright.","Allan prefers to stand and work at his desk.","🧍"],
["strange","[streɪndʒ]","adj","Unusual or surprising.","They are wearing strange masks.","👽"],
["tea","[tiː]","n","Drink from dried leaves.","Many people drink green tea.","🍵"],
["test","[test]","v","To examine quality.","His job is to test the electricity.","🔬"],
["tongue","[tʌŋ]","n","Muscle inside the mouth.","The cat uses its tongue to drink water.","👅"],
["they","[ðeɪ]","pron","Two or more people.","They are playing a fun game.","👥"],
["type","[taɪp]","n","Kind or group.","Tulips are a type of flower.","🔤"],
["very","[ˈveri]","adv","Emphasizes an adjective.","An elephant is a very big animal.","💯"],
["wait","[weɪt]","v","To stay in a place.","She has to wait for the airplane.","⏳"]
]},
{n:20,t:"Albert Einstein",w:[
["accomplish","[əˈkɑːmplɪʃ]","v","To finish something.","He accomplished his goal of running ten miles.","✅"],
["approve","[əˈpruːv]","v","To like or agree with.","Her co-workers approved her new plan.","👍"],
["approximate","[əˈprɑːksɪmət]","adj","Close to exact.","My approximate height is two meters.","📏"],
["barrier","[ˈbæriər]","n","Something that blocks a path.","The Great Wall was a barrier.","🚧"],
["detect","[dɪˈtekt]","v","To notice or find.","He detected the smell of cookies.","👃"],
["duty","[ˈduːti]","n","Something a person must do.","It is parents' duty to care for children.","📋"],
["elementary","[ˌeləˈmentri]","adj","First or most simple.","Children go to elementary school first.","🏫"],
["failure","[ˈfeɪljər]","n","Something not done right.","My cooking ended in failure.","❌"],
["gradual","[ˈɡrædʒuəl]","adj","Happens slowly.","Children learn to read at a gradual pace.","🐢"],
["immigrant","[ˈɪmɪɡrənt]","n","Person who moves to a country.","My parents were immigrants from Poland.","🌎"],
["insert","[ɪnˈsɜːrt]","v","To put in something else.","He inserted an extra sentence.","📥"],
["instant","[ˈɪnstənt]","n","Very short amount of time.","A microwave cooks food in an instant.","⚡"],
["poverty","[ˈpɑːvərti]","n","State of being poor.","Poverty is a problem in many countries.","💔"],
["pretend","[prɪˈtend]","v","To make believe.","The boy liked to pretend he was a king.","🎭"],
["rank","[ræŋk]","n","Place in an order.","The man got to the rank of captain.","🏅"],
["recognition","[ˌrekəɡˈnɪʃn]","n","Getting praise from others.","The hero got recognition for his brave deed.","🏆"],
["refrigerate","[rɪˈfrɪdʒəreɪt]","v","To make cold.","Supermarkets refrigerate fruit to make it last.","❄️"],
["rent","[rent]","n","Money paid to live somewhere.","I pay rent at the start of each month.","🏠"],
["retire","[rɪˈtaɪər]","v","To leave a job.","My father is about to retire from work.","👴"],
["statistic","[stəˈtɪstɪk]","n","Number that tells a fact.","The statistics showed we did just as well.","📊"]
]},
{n:21,t:"From the Earth to the Stars",w:[
["accident","[ˈæksɪdənt]","n","Unexpected event.","He damaged the car in an accident.","💥"],
["astronaut","[ˈæstrənɔːt]","n","Person who goes to space.","The astronaut was walking on the moon.","👨‍🚀"],
["awake","[əˈweɪk]","adj","Not asleep.","Sometimes I lay awake in bed.","👁️"],
["courage","[ˈkɜːrɪdʒ]","n","Feeling of not being afraid.","The man had courage to touch the lion.","🦁"],
["float","[floʊt]","v","To move on water.","The boy's toy boat floated in the pool.","🛶"],
["grant","[ɡrænt]","v","To allow someone to have.","The teacher granted us a break.","✔️"],
["gravity","[ˈɡrævəti]","n","Force making things fall.","There is no gravity in space.","🌍"],
["jewel","[ˈdʒuːəl]","n","Beautiful valuable stone.","A diamond is one of the most expensive jewels.","💎"],
["miner","[ˈmaɪnər]","n","Person who works in a mine.","The miner was looking for gold.","⛏️"],
["mineral","[ˈmɪnərəl]","n","Substance found in Earth.","Rocks are made up of minerals.","🪨"],
["participate","[pɑːrˈtɪsɪpeɪt]","v","To be active and do.","The students participated in the play.","🙋"],
["permission","[pərˈmɪʃn]","n","Act of allowing.","He was given permission to participate.","🔓"],
["pour","[pɔːr]","v","To make liquid flow.","Water poured into the mine.","🌊"],
["raw","[rɔː]","adj","Natural.","His job was to find raw minerals.","🪵"],
["satellite","[ˈsætəlaɪt]","n","Object sent into space.","Part of his job was to send a satellite.","🛰️"],
["scale","[skeɪl]","n","Size.","He was amazed by the scale of space.","📐"],
["skip","[skɪp]","v","To not do something.","The next day, he skipped work.","⏭️"],
["stretch","[stretʃ]","v","To extend.","Jeremy stretched out and grabbed wood.","🙆"],
["telescope","[ˈtelɪskoʊp]","n","Tool for looking far.","He used his telescope to look at stars.","🔭"],
["underground","[ˌʌndərˈɡraʊnd]","adv","Below the Earth.","He worked underground during the day.","⛏️"]
]},
{n:22,t:"The Farm Festival",w:[
["alarm","[əˈlɑːrm]","n","Warns people of danger.","Students heard the fire alarm.","🚨"],
["arrest","[əˈrest]","v","To catch for doing bad.","The man was arrested for breaking the law.","🚔"],
["award","[əˈwɔːrd]","n","Prize for doing well.","He got an award for best grades.","🏆"],
["breed","[briːd]","n","Group of animals.","I like small dog breeds.","🐕"],
["bucket","[ˈbʌkɪt]","n","Round container.","I filled the bucket with water.","🪣"],
["contest","[ˈkɑːntest]","n","Game or race.","The girls had a contest to see who jumped higher.","🥇"],
["convict","[kənˈvɪkt]","v","To prove someone did bad.","He was convicted of the crime.","⚖️"],
["festival","[ˈfestɪvl]","n","Event for celebration.","I heard the song at the music festival.","🎉"],
["garage","[ɡəˈrɑːʒ]","n","Part of house for cars.","My car stays clean in the garage.","🚗"],
["journalist","[ˈdʒɜːrnəlɪst]","n","Person who writes news.","The journalist took notes.","📰"],
["pup","[pʌp]","n","Baby dog.","The pup knocked over the apples.","🐶"],
["qualify","[ˈkwɑːlɪfaɪ]","v","To have the right to.","The winner qualified to win a bag of apples.","✔️"],
["repair","[rɪˈper]","v","To fix.","They had to repair the cart.","🔧"],
["resume","[rɪˈzuːm]","v","To start after a break.","Then, the race resumed.","▶️"],
["rob","[rɑːb]","v","To steal.","The duck tried to rob them.","🦹"],
["slip","[slɪp]","v","To slide and fall.","We are going to slip on the apples!","🥴"],
["somewhat","[ˈsʌmwʌt]","adv","A little.","It was somewhat hard.","🤏"],
["stable","[ˈsteɪbl]","adj","Not changing much.","The cart was not stable.","⚖️"],
["tissue","[ˈtɪʃuː]","n","Soft paper.","The dog gave her a tissue.","🤧"],
["yard","[jɑːrd]","n","Outdoor area around a house.","They had a contest in the yard.","🏡"]
]},
{n:23,t:"48 Hours in Hong Kong",w:[
["best","[best]","adj","Better than all others.","I got the best score on the test.","🥇"],
["card","[kɑːrd]","n","Small piece of plastic/paper.","Adam used his library card.","💳"],
["crowd","[kraʊd]","n","Large group of people.","The crowd waved to the camera.","👥"],
["day","[deɪ]","n","Twenty-four hours.","Two more days until the weekend.","📅"],
["dish","[dɪʃ]","n","Type of cooked food.","My favorite dish is chicken curry.","🍽️"],
["easy","[ˈiːzi]","adj","Not difficult.","Karen's English homework is easy.","😌"],
["experience","[ɪkˈspɪriəns]","v","To do or see something.","Going to the concert was amazing.","🌟"],
["hotel","[hoʊˈtel]","n","Place to stay overnight.","This family is staying at their favorite hotel.","🏨"],
["hour","[ˈaʊər]","n","Sixty minutes.","The man waited over an hour.","⏰"],
["light","[laɪt]","n","Form of energy.","Turn on the light so you can see.","💡"],
["market","[ˈmɑːrkɪt]","n","Place to buy and sell.","I go to the market every weekend.","🛒"],
["plan","[plæn]","v","To arrange details.","It's Sam's turn to plan the party.","📋"],
["price","[praɪs]","n","Amount of money needed.","Julie is checking the price of a sweater.","💵"],
["short","[ʃɔːrt]","adj","Not long or tall.","The days are short in winter.","📉"],
["shop","[ʃɑːp]","v","To visit places to buy.","Tom decided to shop for groceries.","🛍️"],
["station","[ˈsteɪʃn]","n","Where buses and trains stop.","This man is waiting at the train station.","🚉"],
["surprise","[sərˈpraɪz]","v","To cause something unexpected.","His parents decided to surprise him with a puppy.","🎁"],
["system","[ˈsɪstəm]","n","Group of related parts.","This device controls the heating system.","⚙️"],
["taxi","[ˈtæksi]","n","Car and driver you pay.","Gary drives a taxi.","🚕"],
["two","[tuː]","adj","The number 2.","Two friends study together.","2️⃣"]
]},
{n:24,t:"The Doctor's Cure",w:[
["bath","[bæθ]","n","Sitting in a tub of water.","After playing, the boy took a bath.","🛁"],
["bend","[bend]","v","To make not straight.","Lee bent over and picked up paper.","🤸"],
["chew","[tʃuː]","v","To break food with teeth.","I always chew my food carefully.","🦷"],
["disabled","[dɪsˈeɪbld]","adj","Has physical problem.","The disabled man used a wheelchair.","♿"],
["fantastic","[fænˈtæstɪk]","adj","Really good.","The student did a fantastic job.","🌟"],
["fiction","[ˈfɪkʃn]","n","Story that's not true.","I enjoy reading fiction.","📖"],
["flag","[flæɡ]","n","Colored cloth representing something.","Our country has a beautiful flag.","🚩"],
["inspect","[ɪnˈspekt]","v","To look carefully.","The mechanic inspected our car.","🔍"],
["journal","[ˈdʒɜːrnl]","n","Academic magazine.","Mi-young worked on an art journal article.","📰"],
["liquid","[ˈlɪkwɪd]","n","Substance not solid or gas.","Water is the most important liquid.","💧"],
["marvel","[ˈmɑːrvl]","v","To feel surprise and interest.","We marveled at her piano playing.","😲"],
["overcome","[ˌoʊvərˈkʌm]","v","To successfully fix.","She overcame her shyness.","💪"],
["recall","[rɪˈkɔːl]","v","To remember.","She tried to recall what she'd told her friend.","💭"],
["regret","[rɪˈɡret]","v","To wish it hadn't happened.","I regret that I was mean to my sister.","😞"],
["soul","[soʊl]","n","Person's spirit.","Some believe the soul lives after body dies.","👻"],
["sufficient","[səˈfɪʃnt]","adj","Enough.","After a sufficient amount of food, I left.","✅"],
["surgery","[ˈsɜːrdʒəri]","n","Medical treatment with cuts.","I needed surgery to repair my leg.","🏥"],
["tough","[tʌf]","adj","Difficult.","The driving test was very tough.","💪"],
["tube","[tuːb]","n","Pipe for water or air.","The pile of tubes was going to be put in the ground.","🚰"],
["value","[ˈvæljuː]","n","What something is worth.","Your love has greater value than gold.","💎"]
]},
{n:25,t:"How Comet Got His Tail",w:[
["atom","[ˈætəm]","n","Smallest unit of matter.","A molecule is two or more atoms.","⚛️"],
["beautiful","[ˈbjuːtɪfl]","adj","Good to look at.","There was a beautiful sunset.","🌅"],
["breadth","[bredθ]","n","Distance from one side to other.","The breadth of the northern wall is 20 meters.","📏"],
["comet","[ˈkɑːmɪt]","n","Space object with glowing tail.","Comets take decades to orbit a star.","☄️"],
["cover","[ˈkʌvər]","v","To put things over.","The Earth was covered with clouds.","🛡️"],
["despair","[dɪˈsper]","n","Feeling of no hope.","Our salespeople were filled with despair.","😔"],
["form","[fɔːrm]","v","To make or shape.","They formed a new government.","🔨"],
["fragment","[ˈfræɡmənt]","n","Small part.","After the light broke, there were fragments of glass.","🧩"],
["galaxy","[ˈɡæləksi]","n","Large collection of stars.","Our solar system is in our galaxy.","🌌"],
["gloom","[ɡluːm]","n","State of darkness or sadness.","In the gloom, it was hard to see.","🌑"],
["large","[lɑːrdʒ]","adj","Very big.","I was frightened by a large bird.","🐘"],
["moon","[muːn]","n","Natural satellite of Earth.","He flew by beautiful moons.","🌕"],
["radiate","[ˈreɪdieɪt]","v","To release energy.","The star radiated light brighter than ever.","☀️"],
["roam","[roʊm]","v","To move without purpose.","A solitary rock roamed through space.","🚶"],
["solitary","[ˈsɑːləteri]","adj","Alone.","A solitary rock roamed through space.","🚶"],
["spectrum","[ˈspektrəm]","n","Range of colors.","The tail shone with all the colors of the spectrum.","🌈"],
["sphere","[sfɪr]","n","Round object.","The sphere was hundreds of times larger.","⚪"],
["star","[stɑːr]","n","Bright object in sky.","One day it approached a bright star.","⭐"],
["status","[ˈsteɪtəs]","n","Rank.","I wish I had a higher status.","🏅"],
["ugly","[ˈʌɡli]","adj","Not good to look at.","I'm just an ugly rock.","👹"]
]},
{n:26,t:"The Two Captains",w:[
["accuse","[əˈkjuːz]","v","To blame someone.","She accused her brother of breaking her computer.","👆"],
["adjust","[əˈdʒʌst]","v","To change to be better.","He adjusted the old guitar.","🔧"],
["amuse","[əˈmjuːz]","v","To entertain.","The singer amused the crowd.","🎤"],
["coral","[ˈkɔːrəl]","n","Hard colorful material from shells.","The diver admired the beautiful coral.","🪸"],
["cotton","[ˈkɑːtn]","n","Cloth from cotton plant.","I like to wear cotton in summer.","👕"],
["crash","[kræʃ]","v","To hit and break.","The car crashed into the tree.","💥"],
["deck","[dek]","n","Floor of a ship.","A ship stores supplies below its deck.","🚢"],
["engage","[ɪnˈɡeɪdʒ]","v","To do something.","Dad was engaged in sawing wood.","🛠️"],
["firm","[fɜːrm]","adj","Solid but not too hard.","He sleeps better on a firm bed.","🛏️"],
["fuel","[ˈfjuːəl]","n","Creates heat or energy.","Wood is the fuel for this fire.","🔥"],
["grand","[ɡrænd]","adj","Impressive, large.","He had a grand ship.","🏰"],
["hurricane","[ˈhɜːrəkeɪn]","n","Big tropical storm.","Thomas saw a hurricane ahead.","🌀"],
["loss","[lɔːs]","n","Act of losing.","The loss of the ship taught William a lesson.","📉"],
["plain","[pleɪn]","adj","Simple.","His ship was very plain.","⬜"],
["reef","[riːf]","n","Ridge of rock in ocean.","The wind blew the ship into the reef.","🪨"],
["shut","[ʃʌt]","v","To close.","William tried to shut the door.","🚪"],
["strict","[strɪkt]","adj","Having clear rules.","Thomas was strict.","📏"],
["surf","[sɜːrf]","v","To ride on waves.","His crew went surfing.","🏄"],
["task","[tæsk]","n","Piece of work.","He made his crew engage in difficult tasks.","📋"],
["zone","[zoʊn]","n","Area with special purpose.","Thomas told him how to avoid the danger zone.","🗺️"]
]},
{n:27,t:"The Duke and the Minister",w:[
["apology","[əˈpɑːlədʒi]","n","Words showing you are sorry.","The girl wrote the teacher an apology.","🙏"],
["bold","[boʊld]","adj","Not afraid.","The bold man climbed the high mountain.","🦁"],
["bug","[bʌɡ]","n","Small insect.","Birds like eating bugs.","🐛"],
["capture","[ˈkæptʃər]","v","To catch and hold.","James tried to capture the bubbles.","🕸️"],
["duke","[duːk]","n","Man of high rank below king.","The duke ruled over the land.","👑"],
["expose","[ɪkˈspoʊz]","v","To make known what's hidden.","He took off his shirt to expose his costume.","👁️"],
["guilty","[ˈɡɪlti]","adj","Feeling bad for something done.","I felt guilty for taking cookies.","😔"],
["hire","[ˈhaɪər]","v","To pay someone to work.","We hired a man to paint our house.","💼"],
["innocent","[ˈɪnəsnt]","adj","Not guilty.","The judge said the woman was innocent.","😇"],
["language","[ˈlæŋɡwɪdʒ]","n","System of communication.","The reporter spoke a language Sally had never heard.","🗣️"],
["minister","[ˈmɪnɪstər]","n","Important person in government.","The minister of education controls schools.","🏛️"],
["tobacco","[təˈbækoʊ]","n","Plant whose leaves are smoked.","The tobacco in cigarettes is bad for you.","🚬"],
["twin","[twɪn]","n","Two children born at same time.","My sister and I are twins.","👯"],
["witch","[wɪtʃ]","n","Woman with magical powers.","People think witches fly on broomsticks.","🧙‍♀️"]
]},
{n:28,t:"The Fisherman",w:[
["accompany","[əˈkʌmpəni]","v","To join or go with.","My brothers accompanied me to the movie.","👥"],
["bare","[ber]","adj","Plain, not covered.","He likes to walk around in bare feet.","🦶"],
["branch","[bræntʃ]","n","Part of tree with leaves.","The monkey hung from a branch.","🌿"],
["breath","[breθ]","n","Air into and out of lungs.","You can't take a breath under water.","💨"],
["bridge","[brɪdʒ]","n","Built over river to cross.","The old bridge fell into the river.","🌉"],
["cast","[kæst]","v","To throw.","The fisherman cast his line into the water.","🎣"],
["dare","[der]","v","To be brave enough.","He dared to jump out of the airplane.","🪂"],
["electronic","[ɪˌlekˈtrɑːnɪk]","adj","Uses electricity.","I like electronic devices like MP3 players.","📱"],
["inn","[ɪn]","n","Place where travelers rest.","The visitor got a room at the inn.","🏨"],
["net","[net]","n","Bag of strong thread.","The boy caught butterflies in his net.","🕸️"],
["philosophy","[fəˈlɑːsəfi]","n","Way to think about truth and life.","My philosophy is 'live and let live'.","🧠"],
["pot","[pɑːt]","n","Deep round metal container.","Don't touch the pot on the stove.","🍲"],
["seed","[siːd]","n","Hard part of plant or fruit.","I planted the seed in the dirt.","🌱"],
["sharp","[ʃɑːrp]","adj","Has thin edge to cut.","That knife is very sharp.","🔪"],
["sort","[sɔːrt]","n","Type of something.","What sort of instrument do you play?","📦"],
["subtract","[səbˈtrækt]","v","To take away.","We learned how to subtract numbers.","➖"],
["tight","[taɪt]","adj","Hard to move, firmly in place.","The knots were too tight to untie.","🪢"],
["virtual","[ˈvɜːrtʃuəl]","adj","Close to being true.","Because he's popular, Joe is the virtual leader.","💻"],
["weigh","[weɪ]","v","To measure how heavy.","The little dog weighed exactly 3 kilograms.","⚖️"],
["whisper","[ˈwɪspər]","v","To say very quietly.","We have to whisper in the library.","🤫"]
]},
{n:29,t:"Osiris and the Nile",w:[
["abstract","[ˈæbstrækt]","adj","An idea, not physical.","The idea of beauty is abstract.","💭"],
["annual","[ˈænjuəl]","adj","Happens once a year.","The annual family picnic.","📅"],
["clay","[kleɪ]","n","Heavy, wet soil for pots.","She made a bowl out of clay.","🏺"],
["cloth","[klɔːθ]","n","Material for clothes.","His shirt is made of soft cloth.","🧵"],
["curtain","[ˈkɜːrtn]","n","Cloth over a window.","She opened the curtains to let light in.","🪟"],
["deserve","[dɪˈzɜːrv]","v","To be worthy of.","The dog deserved a bone.","🏆"],
["feather","[ˈfeðər]","n","Covers a bird's body.","That bird has orange feathers.","🪶"],
["fertile","[ˈfɜːrtl]","adj","Able to produce good crops.","The farmer grew vegetables in fertile soil.","🌾"],
["flood","[flʌd]","n","Water covers usually dry land.","After three days of rain, there was a flood.","🌊"],
["furniture","[ˈfɜːrnɪtʃər]","n","Tables, chairs, etc.","His living room had few pieces of furniture.","🛋️"],
["grave","[ɡreɪv]","n","Place where dead person is buried.","We visit our grandfather's grave each year.","⚰️"],
["ideal","[aɪˈdiːəl]","adj","Perfect.","It was an ideal fit!","🌟"],
["intelligence","[ɪnˈtelɪdʒəns]","n","Ability to learn.","Because of their intelligence, they explored ideas.","🧠"],
["obtain","[əbˈteɪn]","v","To get.","Isis obtained a grave for him in Egypt.","🎯"],
["religious","[rɪˈlɪdʒəs]","adj","Related to religion.","He led religious events.","⛪"],
["romantic","[roʊˈmæntɪk]","adj","Related to love.","The gods thought Isis had done something romantic.","💕"],
["shell","[ʃel]","n","Hard outer covering.","The people gave him beautiful shells.","🐚"],
["shore","[ʃɔːr]","n","Land along edge of water.","The box washed up on a foreign shore.","🏖️"],
["wheel","[wiːl]","n","Round part that turns.","Osiris taught them how to make wheels.","⚙️"],
["wooden","[ˈwʊdn]","adj","Made of wood.","Set brought a beautiful wooden box.","🪵"]
]},
{n:30,t:"The Kitten and the Caterpillar",w:[
["appliance","[əˈplaɪəns]","n","Equipment for home.","Many homes have appliances like ovens.","🔌"],
["basin","[ˈbeɪsn]","n","Large bowl for washing.","She filled the basin with water.","🚿"],
["broom","[bruːm]","n","Brush with long handle.","My father uses a broom to sweep.","🧹"],
["caterpillar","[ˈkætərpɪlər]","n","Small insect like a worm.","Caterpillars change into butterflies.","🐛"],
["cupboard","[ˈkʌbərd]","n","Furniture for food/items.","We put dishes in the cupboards.","🚪"],
["delicate","[ˈdelɪkət]","adj","Easily broken.","You should hold the baby carefully; she's delicate.","🌸"],
["emerge","[iˈmɜːrdʒ]","v","To come out of.","A groundhog emerged from a hole.","🌱"],
["handicap","[ˈhændikæp]","n","Condition limiting abilities.","Joe has a slight handicap, so he uses a walker.","♿"],
["hole","[hoʊl]","n","Hollow space in solid.","They made a big hole in the wall.","🕳️"],
["hook","[hʊk]","n","Sharp curved metal.","The fish went after the sharp hook.","🪝"],
["hop","[hɑːp]","v","To jump a short distance.","The kangaroo hopped away.","🦘"],
["laundry","[ˈlɔːndri]","n","Clothes to be washed.","He put dirty laundry in a basket.","👕"],
["pursue","[pərˈsuː]","v","To chase or follow.","The mother pursued her child down the hill.","🏃"],
["reluctant","[rɪˈlʌktənt]","adj","Not wanting to do.","She was reluctant to say she saw the robbery.","😐"],
["sleeve","[sliːv]","n","Part of shirt for arms.","Ryan bought a shirt with long sleeves.","👕"],
["spine","[spaɪn]","n","Bones along middle of back.","Our spine helps us stand straight.","🦴"],
["stain","[steɪn]","n","Dirty mark hard to clean.","He had a red stain on his collar.","🎨"],
["strip","[strɪp]","n","Long narrow piece.","Long strips of film held images.","📼"],
["swear","[swer]","v","To promise to do.","I will swear to do my best.","🤝"],
["swing","[swɪŋ]","v","To move back and forth.","He can swing a golf club powerfully.","⛳"]